version: '3'

services:
  # the api
  nestjs:
    build: ./backend
    depends_on:
      - postgres
    networks:
      - db
    ports:
      - "3000:3000"

  # the frontend
  vuejs:
    build: ./frontend
    depends_on:
      - postgres
      - nestjs
    networks:
      - db
    ports:
      - "8080:8080"
  
  # a useful admin page to interact w/ postgres
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    volumes:
      - ~/data/pgadmin:/root/.pgadmin
    networks:
      - db
    ports:
      - "8081:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

  # the database
  postgres:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_DB=4{POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ~/data/postgres:/data/postgres
    networks:
      - db
    ports:
      - "5432:5432"

networks:
  db:
    driver: bridge
