version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wp-data:/var/www/html
    restart: always
    networks:
      - network

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    networks:
      - network
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wp-data:/var/www/html
    depends_on:
      - mariadb
    restart: always
    networks:
      - network
    env_file:
      - .env

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: /home/tgarriss/data/mysql
      o: bind
  wp-data:
    driver: local
    driver_opts:
      type: none
      device: /home/tgarriss/data/wordpress
      o: bind

networks:
  network:
    driver: bridge
