version '3.8'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    hostname: ${MYSQL_SERVER}
    restart: always
    env_file: ./srcs/.env
    volumes:
      - db-volume:${MYSQL_DATADIR}
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    restart: always
    env_file: ./srcs/.env
    volumes:
      - wp-volume:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb


  nginx:
    container_name: nginx
    ports:
      443:443
    restart: always
    env_file: ./srcs/.env
    volumes:
      - wp-volume:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress

networks:
  inception:
    driver: bridge

volumes:
  db-volume:
    driver: local
    driver-opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/mariadb
  wp-volume:
    driver: local
    driver-opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/wordpress
