version: '3'

services:
  nginx:
    container_name: nginx
    build: ./srcs/requirements/nginx/
    ports:
      - 443:443
    volumes:
      - /home/tgarriss/wordpress_data:/var/www/tgarriss.42.fr/wordpress
    networks:
      - network
    restart: always

  mariadb:
    container_name: mariadb
    build: ./srcs/requirements/mariadb/
    volumes:
      - /home/tgarriss/mariadb_data:/var/lib/mysql/
    networks:
      - network
    env_file:
      - .env
    ports:
      - 3306:3306
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./srcs/requirements/wordpress/
    ports:
      - 9000:9000
    env_file:
      - .env
    volumes:
      - /home/tgarriss/wordpress_data:/var/www/tgarriss.42.fr/wordpress/
    networks:
      - network
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/tgarriss/mariadb_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/tgarriss/wordpress_data
      o: bind

networks:
  network:
    driver: bridge
