version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wp-network
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - wp-network
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wp-network
    restart: always

networks:
  wp-network:
    name: wp-network
    driver: bridge
