version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    hostname: ${MYSQL_SERVER}
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATADIR=${MYSQL_DATADIR}
    volumes:
      - db-volume:${MYSQL_DATADIR}
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_EMAIL=${MYSQL_EMAIL}
      - MYSQL_SERVER=${MYSQL_SERVER}
      - WP_USER=${WP_USER}
      - WP_PWD=${WP_PWD}
      - WP_EMAIL=${WP_EMAIL}
    volumes:
      - wp-volume:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb


  nginx:
    container_name: nginx
    build: ./requirements/nginx
    args:
        - DOMAIN_NAME=${DOMAIN_NAME}
        - CERT_CRT=${CERT_CRT}
        - CERT_KEY=${CERT_KEY}
        - MYSQL_SERVER=${MYSQL_SERVER}
    ports:
      - 443:443
    restart: always
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - CERT_CRT=${CERT_CRT}
      - CERT_KEY=${CERT_KEY}
      - MYSQL_SERVER=${MYSQL_SERVER}
    volumes:
      - wp-volume:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress

networks:
  inception:
    driver: bridge

volumes:
  db-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/mariadb
  wp-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/wordpress
