version: '3'

services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html/
    networks:
      - network

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mariadb/
    networks:
      - network
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html/
    networks:
      - network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/tgarriss/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/tgarriss/data/wordpress
      o: bind

networks:
  network:
    driver: bridge
